import 'package:hive/hive.dart';
import 'package:movies_app/movies/domain/entities/movie.dart';

part 'movie_hive_model.g.dart';  // Ensure this file is generated by build_runner

@HiveType(typeId: 1)  // typeId must be unique
class MovieHiveModel {
  @HiveField(0)
  final int id;

  @HiveField(1)
  final String title;

  @HiveField(2)
  final String? backdropPath;

  @HiveField(3)
  final List<int> genreIds;

  @HiveField(4)
  final String overview;

  @HiveField(5)
  final double voteAverage;

  @HiveField(6)
  final String releaseDate;

  MovieHiveModel({
    required this.id,
    required this.title,
    this.backdropPath,
    required this.genreIds,
    required this.overview,
    required this.voteAverage,
    required this.releaseDate,
  });

  // Factory to convert MovieHiveModel to Movie (entity)
  factory MovieHiveModel.fromEntity(Movie movie) => MovieHiveModel(
    id: movie.id,
    title: movie.title,
    backdropPath: movie.backdropPath,
    genreIds: movie.genreIds,
    overview: movie.overview,
    voteAverage: movie.voteAverage,
    releaseDate: movie.releaseDate,
  );

  // Convert MovieHiveModel to Movie entity
  Movie toEntity() => Movie(
    id: id,
    title: title,
    backdropPath: backdropPath,
    genreIds: genreIds,
    overview: overview,
    voteAverage: voteAverage,
    releaseDate: releaseDate,
  );
}
